### ISSUE TITLE
server/GlyphAPI作成

### ISSUE THREAD

**Issue by Meow520** [Doer-org/glyph#3]
📝メモ

### Domain (entities)
- [x] ‘server/src/domain/entity/glyph.go’でapiのデータの型定義
- [x] ‘server/src/domain/repository/glyph.go’でapiの型定義

### Use-case
- [x] ‘server/src/usecase/glyph.go’でapi定義

### Presenter 
- [x] ‘server/src/presentation/json/glyph.go’で外部に渡すときの型を定義
- [ ] ‘server/src/presentation/handler/glyph.go’でresponse定義
- [ ] ‘server/src/presentation/router/glyph.go’でdb接続

**Comment by seipan** [comment]
https://github.com/Doer-org/glyph/tree/main/server/database/mysql/sql
ここにsqlファイル追加してね、スキーマ定義はmiroの感じで、他はuser.go見ながらいい感じに作ってください。
